# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:

  - name: Important Dates
    url: '/#important-dates'
    weight: 1

  - name: General Information
    identifier: about
    weight: 2

  - name: About AMW
    parent: about
    url: '/#about'
    weight: 21

  - name: Registration
    parent: about
    url: '/tbd'
    weight: 22

  - name: Organization
    parent: about
    url: '/organization'
    weight: 23

  - name: Contact
    parent: about
    url: '#contact'
    weight: 23


  - name: Call for Papers
    parent: workshop
    url: '/call'
    weight: 2

  - name: Workshop
    identifier: workshop
    weight: 10

  - name: Program
    parent: workshop
    url: '/tbd'
    weight: 21

  - name: Keynotes
    parent: workshop
    url: '/tbd'
    weight: 30

  - name: School
    identifier: school
    url: '/school'
    weight: 40

  - name: Speakers
    parent: school
    url: '/school#speakers'
    weight: 41
  
  - name: Program
    parent: school
    url: '/school#program'
    weight: 42


  # - name: Organization
  #   url: '/organization'
  #   weight: 50

  - name: Participan Information
    identifier: info
    url: '/venue'
    weight: 60

  - name: Venue
    parent: info
    url: '/venue'
    weight: 61  

  - name: Hotels
    parent: info
    url: '/hotels'
    weight: 62  

  # - name: Registration
  #   url: '#'
  #   weight: 70






  # - name: Previous AWS
  #   url: 'https://easychair.org/cfp/amw2023'
  #   weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
