# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:


  - name: News
    url: '/news'
    weight: 1

  # --------------------------------------------
  # GENERAL INFORMATION
  # --------------------------------------------

  - name: General Information
    identifier: "general-info"
    weight: 2

  - name: About AMW
    parent: "general-info"
    url: '/#about'
    weight: 21

  - name: Dates
    parent: "general-info"
    url: '/#dates'
    weight: 22

  - name: Organization
    parent: "general-info"
    url: '/organization'
    weight: 23

  - name: Contact
    parent: "general-info"
    url: '#contact'
    weight: 24

  - name: Sponsors
    parent: "general-info"
    url: '#sponsors'
    weight: 25

  - name: DEI Statement
    parent: "general-info"
    url: '/dei'
    weight: 26  

  # --------------------------------------------
  # CALL FOR SUBMISSIONS
  # --------------------------------------------

  - name: Call for Submissions
    identifier: submissions
    url: '/submissions'
    weight: 3

  - name: Important Dates
    parent: submissions
    url: '/submissions#important-dates'
    weight: 31

  - name: Call for Papers
    parent: submissions
    url: '/submissions#call-for-papers'
    weight: 32

  - name: Camera-Ready Guidelines
    parent: submissions
    url: '/submissions#camera-ready'
    weight: 32



  # --------------------------------------------
  # Speakers
  # --------------------------------------------

  # - name: Speakers
  #   identifier: speakers
  #   weight: 3
  #   url: '/keynotes'

  # - name: School Speakers
  #   parent: speakers
  #   weight: 42
  #   url: '/speakers'

  # - name: Keynote Speakers
  #   parent: speakers
  #   weight: 42
  #   url: '/keynotes'


  # --------------------------------------------
  # PROGRAM
  # --------------------------------------------

  # - name: Program
  #   identifier: program
  #   weight: 4

  # - name: School Program
  #   parent: program
  #   url: '/program'
  #   weight: 41

  # - name: Workshop Program
  #   parent: program
  #   url: '/program#workshop'
  #   weight: 42

  # - name: Accepted Papers
  #   parent: program
  #   url: '/accepted-papers'
  #   weight: 80  



  # --------------------------------------------
  # WORKSHOP PROGRAM
  # --------------------------------------------

  - name: Workshop
    identifier: workshop
    weight: 4

  - name: Keynotes
    parent: workshop
    weight: 41
    url: '/keynotes'

  - name: Accepted Papers
    parent: workshop
    url: '/accepted-papers'
    weight: 42
    

  - name: Workshop Program
    parent: workshop
    url: '/program#workshop'
    weight: 43
    

  # --------------------------------------------
  # SCHOOL PROGRAM
  # --------------------------------------------

  - name: School
    identifier: school
    url: '/school'
    weight: 40

  - name: Speakers
    parent: school
    url: '/speakers'
    weight: 141
  
  - name: School Program
    parent: school
    url: '/program'
    weight: 142




  # --------------------------------------------
  # PARTICIPANT INFORMATION
  # --------------------------------------------

  - name: Participant Information
    identifier: info
    url: '/venue'
    weight: 60

  - name: Fees
    parent: "info"
    url: '/registration'
    weight: 61

  - name: Registration
    parent: "info"
    url: '/registration#procedure'
    weight: 62

  # - name: Grants
  #   parent: "info"
  #   url: '/grants'
  #   weight: 63

  - name: Venue
    parent: info
    url: '/venue'
    weight: 64  

  - name: Accomodation
    parent: info
    url: '/hotels'
    weight: 65  

  # - name: Banquet
  #   parent: info
  #   url: '/tbd'
  #   weight: 64  


  # --------------------------------------------
  # Others
  # --------------------------------------------

  - name: Grant Program
    url: '/grants'
    weight: 100


  - name: Previous AMW
    identifier: past
    url: 'https://en.wikipedia.org/wiki/Alberto_O._Mendelzon#Alberto_Mendelzon_International_Workshop_on_Foundation_of_Databases_and_the_Web_(AMW)'
    weight: 110

    






