# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:


  - name: Important Dates
    url: '/#important-dates'
    weight: 1

  # --------------------------------------------
  # GENERAL INFORMATION
  # --------------------------------------------

  - name: General Information
    identifier: "general-info"
    weight: 2

  - name: About AMW
    parent: "general-info"
    url: '/#about'
    weight: 21

  - name: Dates
    parent: "general-info"
    url: '/#dates'
    weight: 22

  - name: Organization Officers
    parent: "general-info"
    url: '/organization'
    weight: 23

  - name: Contact
    parent: "general-info"
    url: '#contact'
    weight: 24


  # --------------------------------------------
  # CALL FOR SUBMISSIONS
  # --------------------------------------------

  - name: Call for Submissions
    identifier: submissions
    url: '/submissions'
    weight: 3

  - name: Important Dates
    parent: submissions
    url: '/submissions#important-dates'
    weight: 31

  - name: Call for Papers
    parent: submissions
    url: '/submissions#call-for-papers'
    weight: 32

  - name: Camera-Ready Guidelines
    parent: submissions
    url: '/submissions#camera-ready'
    weight: 32




  # --------------------------------------------
  # Speakers
  # --------------------------------------------

  - name: Speakers
    identifier: speakers
    weight: 3
    url: '/keynotes'

  - name: School Speakers
    parent: speakers
    weight: 42
    url: '/speakers'

  - name: Keynote Speakers
    parent: speakers
    weight: 42
    url: '/keynotes'


  # --------------------------------------------
  # PROGRAM
  # --------------------------------------------

  - name: Program
    identifier: program
    weight: 4

  - name: School Program
    parent: program
    url: '/school'
    weight: 41

  - name: Workshop Program
    parent: program
    url: '/workshop'
    weight: 42

  



  # --------------------------------------------
  # WORKSHOP PROGRAM
  # --------------------------------------------

  # - name: Workshop Program
  #   identifier: workshop
  #   weight: 4

  # - name: Keynote Speakers
  #   parent: workshop
  #   url: '/keynotes'
  #   weight: 41

  # - name: Workshop Full Program
  #   parent: workshop
  #   url: '/workshop'
  #   weight: 42




  # --------------------------------------------
  # SCHOOL PROGRAM
  # --------------------------------------------

  # - name: School Program
  #   identifier: school
  #   url: '/school'
  #   weight: 40

  # - name: Speakers
  #   parent: school
  #   url: '/school#speakers'
  #   weight: 41
  
  # - name: Program
  #   parent: school
  #   url: '/school#program'
  #   weight: 42


  # - name: Organization
  #   url: '/organization'
  #   weight: 50




  # --------------------------------------------
  # PARTICIPANT INFORMATION
  # --------------------------------------------

  - name: Participant Information
    identifier: info
    url: '/venue'
    weight: 60

  - name: Registration
    parent: "info"
    url: '/registration'
    weight: 61

  - name: Venue
    parent: info
    url: '/venue'
    weight: 62  

  - name: Accomodation
    parent: info
    url: '/hotels'
    weight: 63  

  - name: Banquet
    parent: info
    url: '/tbd'
    weight: 64  





  # - name: Previous AWS
  #   url: 'https://easychair.org/cfp/amw2023'
  #   weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
